// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vNXUv4B6ArgwuuLjcsehmNX4QH3QWvs',
    appId: '1:795443018791:web:94157df04549e1968e2202',
    messagingSenderId: '795443018791',
    projectId: 'project-freelance-001',
    authDomain: 'project-freelance-001.firebaseapp.com',
    storageBucket: 'project-freelance-001.appspot.com',
    measurementId: 'G-9GRPYGJX28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-0G-i3l1fO3CU5Q_9qnbQrsBfs4X6zOg',
    appId: '1:795443018791:android:66a6730fb27ba4ff8e2202',
    messagingSenderId: '795443018791',
    projectId: 'project-freelance-001',
    storageBucket: 'project-freelance-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYiGE1oXIVsKUMzcPnB9CjU4KzHYxQ8PE',
    appId: '1:795443018791:ios:4065e909e28b17448e2202',
    messagingSenderId: '795443018791',
    projectId: 'project-freelance-001',
    storageBucket: 'project-freelance-001.appspot.com',
    iosBundleId: 'com.example.tabitha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYiGE1oXIVsKUMzcPnB9CjU4KzHYxQ8PE',
    appId: '1:795443018791:ios:7c3015ec4486f5748e2202',
    messagingSenderId: '795443018791',
    projectId: 'project-freelance-001',
    storageBucket: 'project-freelance-001.appspot.com',
    iosBundleId: 'com.example.tabitha.RunnerTests',
  );
}
